### ISSUE TITLE
This code is Sh*t

### ISSUE THREAD

**Issue by Arciles** [yasincinar/PayU-Error-Messages#1]
write a better code next time dude :dash:

**Comment by yasincinar** [comment]
This is not a brilliant code to save the world. It just helps you to save your time ;)

**Comment by Arciles** [comment]
I don't know man. It's not tidily written and it's only in Turkish. Still thanks for your contribution to the coding world. I believe next time you are gonna write a code and it's gonna change the World :D

**Comment by yasincinar** [comment]
I believe all of us can change :+1:

**Comment by Arciles** [comment]
[http://i1.ytimg.com/vi/Dgosi8Mp41Q/hqdefault.jpg](url)
